language: node_js
sudo: required
before_install:
- npm install -g npm
- npm --version
script:
- npm run build
node_js:
- '8'
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
  email: sargsyan.sargis.89@gmail.com
  api_key:
    secure: pgViNhGBGECiV+HpePYkjtud4RtZ1ZuTuZhcSYRNzOIbRSeii8FEZc2nYcVtlfNcjlbvuQsc1IBnuZyFIkG3/rE/ep4Exee4v1EALvcaAvGm5BtwcqtJM/3q4l88VghvuDf2cdSdWnSN4rExjJFh1iedneZ54tLkqHUP4N4RpkC+LPjHoVr17UeeSa0z16IDVI+OZeNhl0Ir0Rrv+L4mA9oxVsGPFE+arf2jUxMtZSiklF+/oeHmOQUrp5jEuG9fF7FF3KiI3jUxChPgBBUjC/rsrsgBsBpEEK5rsZjsZN27eiGgEVfFXv8Dmpnf49KV++RGkDjrBewDD/vO0m8kCdXZ8PAzar6BoT+N6I1OPa5x9Wfnx2RyDIfFE41FtGPE5ZBOapEdxGaZb5YeceFxarnGdFdzP2pgBXhh9JeZuiTfQ5Prb6wunY/s9wEfE45GZHqs3Ue3dN927Brit9Ipi9sR4u5xR5ObImCZ3+o99Zi4nFPUGHdC47R8sZZILxPE4JwSZRZjVw6nWbwtowvWL/a2cjLLzsGkhkUniq3fat01xxTqlY1XXkHBW0uLhGqAQUfy3xDDp65psW+pK+HD6FnuPTqtmjA7wS3hCor6XdHvZA/XXBkvVrWRTCtofoF0K0i23UkS3ev1Uiq2gDNhCJSkMM7xSyZXzFnlGcp+GyI=
